/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.Usuario;

public class FormPrincipal extends javax.swing.JFrame {

    private Usuario usuario;

    public FormPrincipal(Usuario us) {
        initComponents();
        this.usuario = us;
        this.setLocationRelativeTo(null);
        this.setTitle("Sweet Coffe");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botaoCardapio = new javax.swing.JButton();
        botaoVender = new javax.swing.JButton();
        botaoDeslogar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botaoHV = new javax.swing.JButton();
        botaoSobre = new javax.swing.JButton();
        botaoBuscarUsuarios = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoCardapio.setText("Editar Cardapio");
        botaoCardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCardapioActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCardapio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 190, 50));

        botaoVender.setText("Vender Produtos");
        botaoVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVenderActionPerformed(evt);
            }
        });
        getContentPane().add(botaoVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 190, 50));

        botaoDeslogar.setText("Deslogar");
        botaoDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeslogarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoDeslogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Sweet Coffe");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        botaoHV.setText("Historico de Vendas");
        botaoHV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoHVActionPerformed(evt);
            }
        });
        getContentPane().add(botaoHV, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 190, 50));

        botaoSobre.setText("Sobre");
        botaoSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSobreActionPerformed(evt);
            }
        });
        getContentPane().add(botaoSobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, -1, -1));

        botaoBuscarUsuarios.setText("Buscar Usuarios");
        botaoBuscarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(botaoBuscarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 190, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gradient.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 520, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCardapioActionPerformed
        this.dispose();
        FormCardapio TelaCardapio = new FormCardapio(usuario);
        TelaCardapio.setVisible(true);
    }//GEN-LAST:event_botaoCardapioActionPerformed

    private void botaoVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVenderActionPerformed
        this.dispose();
        FormVendas TelaVenda = new FormVendas(usuario);
        TelaVenda.setVisible(true);
    }//GEN-LAST:event_botaoVenderActionPerformed

    private void botaoDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeslogarActionPerformed
        FormLogin TelaLogin = new FormLogin();
        this.dispose();
        TelaLogin.setVisible(true);
    }//GEN-LAST:event_botaoDeslogarActionPerformed

    private void botaoHVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoHVActionPerformed
        this.dispose();
        FormHistoricoVendas TelaHistoricoVendas = new FormHistoricoVendas(usuario);
        TelaHistoricoVendas.setVisible(true);
    }//GEN-LAST:event_botaoHVActionPerformed

    private void botaoSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSobreActionPerformed
        String descricao = """
                             Este programa foi feito para aprendizado de P.O.O.
                             Além disso para aprendizado de manipulação de DataBases.""";

        String nomeDev = "Desenvolvedor: [Pedro Borges Casaroti]";
        String codigo = "Código: [838708]";

        JOptionPane.showMessageDialog(this, descricao + "\n\n" + nomeDev + "\n" + codigo,
                "Informações do Projeto", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_botaoSobreActionPerformed

    private void botaoBuscarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarUsuariosActionPerformed
        this.dispose();
        FormBuscarUsuario TelaBuscarUsuario = new FormBuscarUsuario(usuario);
        TelaBuscarUsuario.setVisible(true);
    }//GEN-LAST:event_botaoBuscarUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscarUsuarios;
    private javax.swing.JButton botaoCardapio;
    private javax.swing.JButton botaoDeslogar;
    private javax.swing.JButton botaoHV;
    private javax.swing.JButton botaoSobre;
    private javax.swing.JButton botaoVender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
